# 菜单
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  About: /about
  link: /friends
# github账号
Github: https://github.com/yuang01/hexo-theme-bamboo

# 网站logo
logo: /medias/logo.png

# 网站 favicon
favicon: /favicon.ico # or .png .jpg .svg .gif .jpeg .ico

# 頂部导航固定
headMenuFixed: true

# 首页轮播图设置
swiper:
  showPrevNext: true # 是否显示左右切换按钮
  showIndicators: true  # 是否显示指示器
  autoplay: true # 是否自动轮播
  loop: true # 让轮播看起来是循环的, 例如false的话，到达最后一个轮播图的时候，右按钮不能点击
  delay: 5000 # 切换延迟时间
  effect: 'slide' # 'fade'
  textAnimated: 'fadeInDown' # 文字动画，属性使用 animate.css, https://daneden.github.io/animate.css/
  textDuration: '0.2s' # 文字动画持续时间（单位秒）
  textDelay: '0.1s' # 文字动画延迟时间（单位秒）
  # 当没有文章设置swiper: true时候，轮播图会显示以下default默认内容，可自行切换对应内容
  defaultImg: '/medias/14.png' # 图片，没有则随机选取
  defaultTile: 'Hexo-theme-Bamboo' # 标题
  defaultDesc: '大家好，这是一个Hexo主题，希望这款主题能得到你的喜爱' #描 述
  defaultMoreLink: 'https://github.com/yuang01/hexo-theme-bamboo' # 阅读更多链接 
  defaultBtnText: 'Download theme' # 阅读更多右边的按钮的文字
  defaultBtnLink: 'https://github.com/yuang01/hexo-theme-bamboo' # 阅读更多右边的按钮的链接

# 回到顶部
goTop: 
  on: true

# 图片点击放大功能
fancybox: 
  on: true

# 统计网站访问数量
busuanzi:
  on: true

# 标签页和分类页中，显示这个标签或者分类在文章中出现的次数
show_count: true

# 打赏功能
donate:
  on: true
donate_message: 你的赏识是我前进的动力
# 支付宝打赏图片相对路径
Alipay: '/medias/zfb.jpg'
# 微信打赏图片相对路径
WeChatpay: '/medias/wx.jpg'

# 分享功能
sharejs: 
  on: true
  sites: twitter,facebook,google,qq,qzone,wechat,weibo,douban,linkedin

# 点击出现爱心效果
clicklove:
  on: true

# 全文搜索功能
search:
  on: true

# 文章详情页底部显示上一篇文章和下一篇文章
postNav:
  on: true

# 复制成功提示
copy:
  on: true

# 文章详情页的标题是否显示在顶部图片中, false则显示在文章内容顶部
postTitleTop:
  on: true

# 输入框打字特效
inputEffects:
  on: true

# live-2d(左下角动画人物)
live2d:
  on: true

# 首页文章列表滚动动画，详情参照https://github.com/michalsnik
aos:
  on: true
  animate: 'fade-up' # animate, 更多选项请参考 https://github.com/michalsnik/aos#animations
  offset: 120 # offset (in px) from the original trigger point
  delay: 0 # values from 0 to 3000, with step 50ms
  duration: 400 # values from 0 to 3000, with step 50ms
  easing: 'ease' # default easing for AOS animations
  once: true # whether animation should happen only once - while scrolling down
  mirror: false # whether elements should animate out while scrolling past them
  anchorPlacement: 'top-bottom' # defines which position of the element regarding to window should trigger the animation

# 添加 Google Analytics 配置
googleAnalytics:
  on: false
  id:

# 添加 baidu Analytics 配置
baiduAnalytics:
  on: false
  id:

# 百度搜索资源平台提交链接
baiduPush: true

# 文章目录
toc:
  on: true
  heading: h2, h3, h4

# 音乐
# 是否在首页显示音乐.
music:
  on: true
  autoHide: true    # hide automaticaly
  server: netease   #require	music platform: netease, tencent, kugou, xiami, baidu
  type: playlist    #require song, playlist, album, search, artist
  id: 442274724     #require	song id / playlist id / album id / search keyword
  fixed: true       # 开启吸底模式，建议开启
  autoplay: false   # 是否自动播放
  theme: '#42b983'
  loop: 'all'       # 音频循环播放, 可选值: 'all', 'one', 'none'
  order: 'random'   # 音频循环顺序, 可选值: 'list', 'random'
  preload: 'auto'   # 预加载，可选值: 'none', 'metadata', 'auto'
  volume: 0.7       # 默认音量，请注意播放器会记忆用户设置，用户手动设置音量后默认音量即失效
  listFolded: true  # 列表默认折叠
  hideLrc: true     # 隐藏歌词

# 关于我
baseInfo:
  on: true
  age: 99 # 年龄
  sex: '男' # 性别
  coordinate: '火星' # 坐标
  status: '划水中' # 状态

# 关于我 技能
skills:  # color or #000 技能
  on: true
  data:
    HTML5:
      background: 'linear-gradient(45deg, #ff9a9e 0%, #fad0c4 99%, #fad0c4 100%)'
      percent: 90%
    JavaScript:
      background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)'
      percent: 85%
    Node.js:
      background: 'linear-gradient(to right, #43e97b 0%, #38f9d7 100%)'
      percent: 50%
    CSS:
      background: 'linear-gradient(to right, #eea2a2 0%, #bbc1bf 19%, #57c6e1 42%, #b49fda 79%, #7ac5d8 100%)'
      percent: 70%
    Vue:
      background: 'linear-gradient(to top, #0ba360 0%, #3cba92 100%)'
      percent: 90%
    uni-app:
      background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)'
      percent: 75%
    jquery: 
      background: 'linear-gradient( 135deg, #97ABFF 10%, #123597 100%)'
      percent: 70%
    H5: 
      background: 'linear-gradient(to top, #00c6fb 0%, #005bea 100%)'
      percent: 75%
    APP:  
      background: 'linear-gradient( 135deg, #69FF97 10%, #00E4FF 100%)'
      percent: 75%

# 关于我 社交账号
socialAccounts: 
  on: true
  data:
    QQ:
      icon: fa fa-qq
      name: 1730241541
      url: 'http://www.baidu.com'
    微信:
      icon: fa fa-weixin
      name: 1730241541
      url: 'http://www.baidu.com'

# 关于我 游戏
games:
  on: true
  data:
    王者荣耀:
      img: 'https://pic2.zhimg.com/80/v2-54730a36304842b86a57a237b8b39945_720w.jpg?source=1940ef5c'
    英雄杀:
      img: 'https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=1909008358,1888649581&fm=26&gp=0.jpg'
    和平精英:
      img: 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1595596612190&di=dbf2030780758c4724ecb1f07f2f4f73&imgtype=0&src=http%3A%2F%2Fimgup04.51wxjz.com%2F51wxjz%2F2019-06%2F05%2F09%2F15596983468928_0.png'
    英雄联盟:
      img: 'https://ss1.bdstatic.com/70cFuXSh_Q1YnxGkpoWK1HF6hhy/it/u=3035766587,2822701570&fm=26&gp=0.jpg'

# 关于我 书籍
books:
  on: true
  data:
    明朝那些事儿:
      img: 'https://ss0.bdstatic.com/70cFvHSh_Q1YnxGkpoWK1HF6hhy/it/u=2736238052,2078148140&fm=26&gp=0.jpg'
    春秋左传:
      img: 'https://pic2.zhimg.com/50/v2-6f33f60312de25ddcb795fc81ee91b38_720w.jpg?source=54b3c3a5'
    孙子兵法:
      img: 'https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=710999414,899378807&fm=26&gp=0.jpg'

#版权信息  coryRyght
copyright:
  on: true

# 文章置顶
topArticle:
  on: true

# valine 评论
valine:
  on: false
  appid:
  appkey:
  avatar: '' # 匿名者头像选项 https://valine.js.org/avatar.html
  placeholder: '客官，说点什么吧'

# miniValine
miniValine:
  on: false
  appid: 
  appkey: 
  avatar: '' # 匿名者头像选项 https://valine.js.org/avatar.html
  placeholder: '客官，说点什么吧'

# 来必力评论
livere:
  on: false
  livere_uid:

# gitment 评论
gitment:
  on: false
  gitment_owner:       #你的 GitHub ID
  gitment_repo: #存储评论的 repo
  clientId: #client ID
  clientSecret:       #client secret

# 畅言评论
changyan:
  on: false
  appId:
  conf:

# gitalk评论
gitalk:
  on: false         # 用来做启用判断可以不用
  owner:        #Github 用户名,
  repo:        #储存评论issue的github仓库名
  admin:        #Github 用户名,
  clientID:      #`Github Application clientID`
  clientSecret:  #`Github Application clientSecret`

# 归档页面图片 or 'http://xxx'
archiveImg: '/medias/archiveImg.png'
# 标签页面图片
tagImg: '/medias/tag.png'
# 标签详情页面图片
tagDetailImg: '/medias/tagDetail.png'
# 分类页面图片
categoriesImg: '/medias/categories.png'
#分类详情页面图片
categoryDetailImg: '/medias/categoryDetail.png'
# 关于我页面图片
aboutImg: '/medias/about.png'
# 友情链接页面图片
friendsImg: '/medias/friends.png'

# 文章图片
imgs:
- '/medias/1.png'
- '/medias/2.png'
- '/medias/3.png'
- '/medias/4.png'
- '/medias/5.jpg'
- '/medias/6.jpg'
- '/medias/7.jpg'
- '/medias/8.png'
- '/medias/9.png'
- '/medias/10.jpg'
- '/medias/11.png'
- '/medias/12.png'
- '/medias/13.png'
- '/medias/14.png'
- '/medias/15.png'
- '/medias/16.png'
- '/medias/17.png'

CDN:
  valine: https://cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
  iconfont: https://at.alicdn.com/t/font_1911880_c1nvbyezg17.css
  fontAwesome: https://cdn.bootcdn.net/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  aplayer: https://cdn.bootcdn.net/ajax/libs/aplayer/1.10.1/APlayer.min.js
  Meting: https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js
  MiniValine: https://unpkg.com/minivaline/dist/MiniValine.min.js
  livere: https://cdn-city.livere.com/js/embed.dist.js
  gitmentCss: https://imsun.github.io/gitment/style/default.css
  gitmentJs: https://imsun.github.io/gitment/dist/gitment.browser.js
  gitalkCss: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css
  gitalkJs: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  busuanzi: //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  ayuCss: https://cdn.jsdelivr.net/npm/v-plugs-ayu/lib/ayu.css
  ayuJs: https://cdn.jsdelivr.net/npm/v-plugs-ayu/lib/ayu.umd.min.js
  copyRight: https://creativecommons.org/licenses/by-nc-nd/4.0/
  live2d: https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget@latest/autoload.js
